/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USC;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import connections_bd.Conexion;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author CesarCuellar
 */
public class FrmAgregarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarAlumno
     */
    Conexion cn;
    DefaultTableModel modelo;
    public FrmAgregarAlumno() {
        initComponents();
        jPanel3.setSize(830, 600);
        Fondo.setSize(830, 600);
        rsscalelabel.RSScaleLabel.setScaleLabel(Fondo,"src/Recursos/Fondodef.jpg");
        setLocationRelativeTo(this);    
        cn=new Conexion();
        cn.conectar();
        modelo = (DefaultTableModel) TablaAlumnos.getModel();
        listarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cbDepart = new javax.swing.JComboBox<>();
        cbSexo = new javax.swing.JComboBox<>();
        txtProvincia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Foto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAgregarAlumno = new javax.swing.JButton();
        btnModificarAlumno = new javax.swing.JButton();
        btnEliminarAlumno = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        txtnomimagen = new javax.swing.JTextField();
        ScrollPane = new javax.swing.JScrollPane();
        TablaAlumnos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 130));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 280, 30));

        txtDNI.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtDNI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 30));

        txtNombre.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DNI");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Paterno");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 295, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 30, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellido Materno");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Departamento");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dirección");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 256, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Provincia");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 217, -1, -1));

        txtMaterno.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtMaterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 280, 30));

        txtPaterno.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtPaterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 280, 30));

        txtDireccion.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 30));

        cbDepart.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        cbDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali" }));
        cbDepart.setBorder(null);
        cbDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartActionPerformed(evt);
            }
        });
        jPanel2.add(cbDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 280, 30));

        cbSexo.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        cbSexo.setBorder(null);
        jPanel2.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 280, 30));

        txtProvincia.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtProvincia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvinciaActionPerformed(evt);
            }
        });
        jPanel2.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 280, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 410, 390));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 130));

        Foto.setAlignmentY(0.0F);
        Foto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Foto.setMaximumSize(new java.awt.Dimension(160, 186));
        Foto.setMinimumSize(new java.awt.Dimension(160, 186));
        Foto.setPreferredSize(new java.awt.Dimension(160, 186));

        btnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        btnRegresar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/REGRE.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregarAlumno.setBackground(new java.awt.Color(153, 255, 153));
        btnAgregarAlumno.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnAgregarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnAgregarAlumno.setBorder(null);
        btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnoActionPerformed(evt);
            }
        });

        btnModificarAlumno.setBackground(new java.awt.Color(255, 255, 153));
        btnModificarAlumno.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnModificarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-editar.png"))); // NOI18N
        btnModificarAlumno.setBorder(null);
        btnModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlumnoActionPerformed(evt);
            }
        });

        btnEliminarAlumno.setBackground(new java.awt.Color(102, 153, 255));
        btnEliminarAlumno.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnEliminarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar.png"))); // NOI18N
        btnEliminarAlumno.setBorder(null);
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(255, 153, 0));
        btnExportar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/archivo-pdf.png"))); // NOI18N
        btnExportar.setText("Exportar reporte en PDF");
        btnExportar.setBorder(null);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(204, 153, 255));
        btnNuevo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-de-nuevo-documento.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnImagen.setBackground(new java.awt.Color(204, 204, 204));
        btnImagen.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/adjuntar.png"))); // NOI18N
        btnImagen.setText("Adjuntar imagen del alumno");
        btnImagen.setBorder(null);
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        txtnomimagen.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtnomimagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnomimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomimagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtnomimagen))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 370, 390));

        ScrollPane.setBackground(new java.awt.Color(30, 30, 30));
        ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrollPaneMouseClicked(evt);
            }
        });

        TablaAlumnos.setBackground(new java.awt.Color(0, 102, 153));
        TablaAlumnos.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        TablaAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        TablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombres", "Apellido Paterno", "Apellido Materno", "Departamento", "Provincia", "Dirección", "Correo", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAlumnosMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(TablaAlumnos);

        getContentPane().add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 790, 190));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setPreferredSize(null);
        jPanel3.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    FrmMenu vermenu = new FrmMenu();
    vermenu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * Método que agrega un alumno a la lista de Alumnos
     * @param evt 
     */
    private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoActionPerformed
    AgregarAlumnos();
    listarAlumnos();
    nuevo();
    }//GEN-LAST:event_btnAgregarAlumnoActionPerformed
    public void AgregarAlumnos(){
        String DNI = this.txtDNI.getText();
        String Nombres = this.txtNombre.getText();
        String Apellido_Paterno = this.txtPaterno.getText();
        String Apellido_Materno = this.txtMaterno.getText();
        String Departamento = this.cbDepart.getSelectedItem().toString();
        String Provincia = this.txtProvincia.getText();
        String Direccion = this.txtDireccion.getText();
        String Correo = this.txtCorreo.getText();
        String Sexo = this.cbSexo.getSelectedItem().toString();
        try {
            if (DNI.equals("") || Nombres.equals("") || Apellido_Paterno.equals("") || Apellido_Materno.equals("") || Departamento.equals("") || Provincia.equals("") || Direccion.equals("") || Correo.equals("") || Sexo.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar Datos");
            }else{
                String insertar = "INSERT INTO alumnos (id_alumno,DNI,Nombres,Apellido_Paterno,Apellido_Materno,Departamento,Provincia,Direccion,Correo,Sexo) VALUES (NULL,'" + DNI + "','" + Nombres + "','" + Apellido_Paterno + "','" + Apellido_Materno + "','" + Departamento + "','" + Provincia + "','" + Direccion + "','" + Correo + "','" + Sexo + "')";
                Statement st = cn.conectar().createStatement();
                int rs = st.executeUpdate(insertar);
                if (rs > 0) {
                    JOptionPane.showMessageDialog(null, "Se agregó al alumno correctamente.");
                    limpiarTabla();
                    String insertarusuario = "INSERT INTO usuario (usuario,contraseña) VALUES ('"+DNI+"','"+DNI+"')";
                    st.executeUpdate(insertarusuario);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar al alumno.");
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        } 
    }
    public void listarAlumnos(){
        try {
            limpiarTabla();
            String listar = "SELECT * FROM alumnos ORDER BY id_alumno";
            Statement st = cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(listar);
            Object[] persona = new Object[10];
            modelo = (DefaultTableModel) this.TablaAlumnos.getModel();
            while (rs.next()) {
                persona[0] = rs.getString("id_alumno");
                persona[1] = rs.getString("DNI");
                persona[2] = rs.getString("Nombres");
                persona[3] = rs.getString("Apellido_Paterno");
                persona[4] = rs.getString("Apellido_Materno");
                persona[5] = rs.getString("Departamento");
                persona[6] = rs.getString("Provincia");
                persona[7] = rs.getString("Direccion");
                persona[8] = rs.getString("Correo");
                persona[9] = rs.getString("Sexo");
                modelo.addRow(persona);
            }
            TablaAlumnos.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    void limpiarTabla(){
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    void Modificar() {
        String rutaIcono = "";
        String DNI = this.txtDNI.getText();
        String Nombres = this.txtNombre.getText();
        String Apellido_Paterno = this.txtPaterno.getText();
        String Apellido_Materno = this.txtMaterno.getText();
        String Departamento = this.cbDepart.getSelectedItem().toString();
        String Provincia = this.txtProvincia.getText();
        String Direccion = this.txtDireccion.getText();
        String Correo = this.txtCorreo.getText();
        String Sexo = this.cbSexo.getSelectedItem().toString();
        ImageIcon icono = (ImageIcon) Foto.getIcon();
        if (icono != null){
            rutaIcono = icono.getDescription();
        }
        String sql = "UPDATE alumnos SET DNI='"+ DNI +"',Nombres='"+Nombres +"', Apellido_Paterno='"+Apellido_Paterno+"', Apellido_Materno='"+Apellido_Materno+"',Departamento='"+Departamento+"',Provincia='"+Provincia+"', Direccion='"+Direccion+"', Correo='"+Correo+"', Sexo='"+Sexo+"', ruta_foto='"+rutaIcono+"' WHERE DNI="+ DNI;
        try {
            if (DNI != null || Nombres != null || Apellido_Paterno != null || Apellido_Materno != null || Departamento != null || Provincia != null || Direccion != null || Correo != null || Sexo != null) {
                Statement st = cn.conectar().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Alumno modificado");
                limpiarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Error...!!!");
            }
       } catch (Exception e) {
       }
    }
    void Eliminar() {
        String DNI = this.txtDNI.getText();
        String eliminar = "DELETE FROM alumnos where DNI=" + DNI;        
        int fila = TablaAlumnos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,"Alumno no Seleccionado");
        } else {
                try {
                Statement st = cn.conectar().createStatement();
                st.executeUpdate(eliminar);
                JOptionPane.showMessageDialog(null, "Alumno Eliminado");
                limpiarTabla();
                String eliminarusuario = "DELETE FROM usuario WHERE usuario="+DNI;
                st.executeUpdate(eliminarusuario);
                }catch(Exception e){
                }  
        }
    }
    void nuevo() {
    txtDNI.setText("");
    txtDNI.requestFocus();
    txtNombre.setText("");
    txtPaterno.setText("");
    txtMaterno.setText("");
    txtProvincia.setText("");
    txtDireccion.setText("");
    txtCorreo.setText("");
    cbDepart.setSelectedIndex(0);
    cbSexo.setSelectedIndex(0);
    Foto.setIcon(null);
    }

    private void txtProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvinciaActionPerformed

    private void btnModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlumnoActionPerformed
    Modificar(); 
    listarAlumnos();
    nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarAlumnoActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
    Eliminar();
    listarAlumnos();
    nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
    Document documento = new Document(PageSize.A4.rotate());
    try{
        String ruta = System.getProperty("user.home");
        PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte Alumnos.pdf"));
        Paragraph parrafo = new Paragraph();
        parrafo.setAlignment(Chunk.ALIGN_CENTER);
        parrafo.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD,BaseColor.DARK_GRAY));
        parrafo.add("Reporte de Alumnos \n\n");
        
        documento.open();
        
        documento.add(parrafo);
        
        //Crear una tabla
        PdfPTable tabla = new PdfPTable(10);
        
        tabla.setWidthPercentage(100); // Ancho de la tabla en porcentaje del ancho de la página
        tabla.setSpacingBefore(10f); // Espaciado antes de la tabla
        tabla.setSpacingAfter(10f); // Espaciado después de la tabla
        
        // Crear una fuente
        Font font = FontFactory.getFont(FontFactory.HELVETICA, 9, Font.NORMAL);
        Font headerfont = FontFactory.getFont(FontFactory.HELVETICA, 10);

        // Definir los anchos relativos de las columnas
        float[] columnWidths = {1f, 2f, 4f, 2f, 2f, 3f, 2f, 2f, 3f, 1.5f};
        tabla.setWidths(columnWidths);
        
        // Array con los encabezados
        String[] encabezados = {"ID", "DNI", "Nombres", "Apellido Paterno","Apellido Materno", "Departamento", "Provincia","Direccion", "Correo", "Sexo"};
        
        // Añadir encabezados a la tabla
        for (String encabezado : encabezados) {
            PdfPCell celda = new PdfPCell(new Paragraph(encabezado, headerfont));
            celda.setHorizontalAlignment(Element.ALIGN_CENTER); // Alinea la celda
            tabla.addCell(celda); // Añade la celda a la tabla
        }
        
        // Conectar a la base de datos
        try{
          String pdf = "SELECT * FROM alumnos";
          Statement st = cn.conectar().createStatement();
          ResultSet rs = st.executeQuery(pdf);
          if(rs.next()){
              do
              {
                // Añadir los datos del ResultSet a la tabla
                for (int i = 1; i <= 10; i++){
                    PdfPCell celda = new PdfPCell(new Paragraph(rs.getString(i), font));
                    celda.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(celda);
                }
              }while(rs.next());
              //Añadir la tabla
              documento.add(tabla);
          }
        }catch(DocumentException | SQLException e){
        }
        documento.close();
        JOptionPane.showMessageDialog(null,"Reporte creado");
    }catch(DocumentException | HeadlessException | FileNotFoundException e){
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    private void ScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ScrollPaneMouseClicked

    private void TablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAlumnosMouseClicked
        int row = TablaAlumnos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "No se seleccionó");
        } else {
            String DNI = (String) TablaAlumnos.getValueAt(row, 1);
            try{
            String foto = "SELECT ruta_foto FROM alumnos WHERE DNI="+DNI;
            Statement st = cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(foto);
            if(rs.next())
            {
              String ruta = rs.getString("ruta_foto");
              ImageIcon icon = new ImageIcon(ruta);
              Foto.setIcon(icon);
            }
            }catch(SQLException e)
            {
            }
            String Nombres = (String) TablaAlumnos.getValueAt(row, 2);
            String Paterno = (String) TablaAlumnos.getValueAt(row, 3);
            String Materno = (String) TablaAlumnos.getValueAt(row, 4);
            String Departamento = (String) TablaAlumnos.getValueAt(row, 5);
            String Provincia = (String) TablaAlumnos.getValueAt(row, 6);
            String Direccion = (String) TablaAlumnos.getValueAt(row, 7);
            String Correo = (String) TablaAlumnos.getValueAt(row, 8);
            String Sexo = (String) TablaAlumnos.getValueAt(row, 9);
            txtDNI.setText(DNI);
            txtNombre.setText(Nombres);
            txtPaterno.setText(Paterno);
            txtMaterno.setText(Materno);
            cbDepart.setSelectedItem(Departamento);
            txtProvincia.setText(Provincia);
            txtDireccion.setText(Direccion);
            txtCorreo.setText(Correo);
            cbSexo.setSelectedItem(Sexo);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaAlumnosMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
    JFileChooser archivo = new JFileChooser();
    FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
    archivo.setFileFilter(filtrado);
    int ventana = archivo.showOpenDialog(null);
    if(ventana == JFileChooser.APPROVE_OPTION)
    {
        File file = archivo.getSelectedFile();
        txtnomimagen.setText(String.valueOf(file));
        Image foto = getToolkit().getImage(txtnomimagen.getText());
        foto = foto.getScaledInstance(160, 186, Image.SCALE_DEFAULT);
        Foto.setIcon(new ImageIcon(foto));
    }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartActionPerformed

    private void txtnomimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomimagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomimagenActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Foto;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable TablaAlumnos;
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnModificarAlumno;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbDepart;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtnomimagen;
    // End of variables declaration//GEN-END:variables
}
