
package USC;
import connections_bd.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FrmAsignar extends javax.swing.JFrame {
   
    Conexion cn;
    DefaultTableModel modelo;
    public FrmAsignar() {
        initComponents();
        setLocationRelativeTo(this);
        cn = new Conexion();
        cn.conectar();
        modelo = (DefaultTableModel) Tablasignar.getModel();
        rsscalelabel.RSScaleLabel.setScaleLabel(Fondo,"src/Recursos/Fondodef.jpg");
        cargarCursos();
        cargarDocentes();  
        listarCursos();
    }
    private void cargarDocentes(){
        try { 
            String listar = "SELECT *from docentes";
            Statement st =cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(listar);
            while(rs.next()){
                String[]datos = new String[2];
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
               this.cbodocente.addItem(datos[0]+"-"+datos[1]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmAgregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
       private void cargarCursos(){
        try {
            String listar = "SELECT *from cursos";
            Statement st =cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(listar);
            while(rs.next()){
               String[]datos = new String[2];
               datos[0] = rs.getString(1);
               datos[1] = rs.getString(2);
               this.cboCurso.addItem(datos[0]+"-"+datos[1]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmAgregarCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablasignar = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbodocente = new javax.swing.JComboBox<>();
        lbdocente = new javax.swing.JLabel();
        lbcurso = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        btnreturn = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignar curso");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Asignar curso");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 25, -1, -1));

        jScrollPane1.setToolTipText("");

        Tablasignar.setBackground(new java.awt.Color(0, 102, 153));
        Tablasignar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "ID Docente", "ID Curso"
            }
        ));
        Tablasignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablasignarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablasignar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 199, 570, 160));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 180));

        cbodocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodocenteActionPerformed(evt);
            }
        });

        lbdocente.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbdocente.setForeground(new java.awt.Color(255, 255, 255));
        lbdocente.setText("Docente");

        lbcurso.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbcurso.setForeground(new java.awt.Color(255, 255, 255));
        lbcurso.setText("Curso");

        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });

        btnreturn.setBackground(new java.awt.Color(255, 102, 102));
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/REGRE.png"))); // NOI18N
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        btnagregar.setBackground(new java.awt.Color(153, 255, 153));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(153, 153, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-eliminar.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbodocente, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbodocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbdocente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcurso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnagregar)
                            .addComponent(btneliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreturn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 64, -1, 120));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 620, 368));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, 368));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void Agregarcurso(){
        String Docente = this.cbodocente.getSelectedItem().toString();
        java.lang.String[] parts = Docente.split("-");
        String Docente1 = parts[0];
        String curso = this.cboCurso.getSelectedItem().toString();
        java.lang.String[] parts2 = curso.split("-");
        String curso1 = parts2[0]; 
        try {
            if (Docente.equals("") || curso.equals("")){
                JOptionPane.showMessageDialog(null, "Debe Ingresar Datos");
            } else {
                String insertar = "INSERT INTO carga_lectiva (id_carga,id_Docente,id_Curso) VALUES (NULL,'" + Docente1 + "','" + curso1 + "')";
                Statement st = cn.conectar().createStatement();
                int rs = st.executeUpdate(insertar);
                if (rs > 0) {
                    JOptionPane.showMessageDialog(null, "Se agregó designo el curso correctamente.");                  
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo asignar el curso.");
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }     
    }
    void Eliminar() {
        
        int fila = Tablasignar.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,"curso no Seleccionado");
        } else {
            int id = Integer.parseInt((String)Tablasignar.getValueAt(fila,0).toString());
                try {
                Statement st = cn.conectar().createStatement();
               
                JOptionPane.showMessageDialog(null, "curso Eliminado");
                limpiarTabla();
                String eliminarusuario = "DELETE FROM carga_lectiva WHERE carga_lectiva.id_carga="+id;
                st.executeUpdate(eliminarusuario);
                }catch(Exception e){
                }  
        }
    }
    private void cbodocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodocenteActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
    FrmMenu vermenu = new FrmMenu();
    vermenu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        Agregarcurso();
        limpiarTabla();
        listarCursos();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        Eliminar();
        limpiarTabla();
        listarCursos();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void TablasignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablasignarMouseClicked

    }//GEN-LAST:event_TablasignarMouseClicked

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCursoActionPerformed

    void limpiarTabla(){
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    public void listarCursos(){
        try {
            limpiarTabla();
            String listar = "SELECT * FROM carga_lectiva ORDER BY id_carga";
            Statement st = cn.conectar().createStatement();
            ResultSet rs = st.executeQuery(listar);
            Object[] persona = new Object[3];
            modelo = (DefaultTableModel) this.Tablasignar.getModel();
            while (rs.next()) {
                persona[0] = rs.getString("id_carga");
                persona[1] = rs.getString("id_Docente");
                persona[2] = rs.getString("id_Curso");
             
                modelo.addRow(persona);
            }
            Tablasignar.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAsignar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTable Tablasignar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnreturn;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cbodocente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcurso;
    private javax.swing.JLabel lbdocente;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
