/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package USC;

import connections_bd.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */

public class FrmAgregarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form FrmVerMatricula
     */
    Conexion cn;
    public FrmAgregarMatricula() {
        initComponents();
        setLocationRelativeTo(this);
        cn=new Conexion();
        cn.conectar();
        cargarCursosEnComboBox();
        rsscalelabel.RSScaleLabel.setScaleLabel(Fondo,"src/Recursos/Fondodef.jpg");
        informacion();
    }
     private void cargarCursosEnComboBox() {
        Conexion conexion = new Conexion();
        try (Connection con = conexion.conectar();
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT nombre_curso FROM cursos")) {

            while (rs.next()) {
                jcurso.addItem(rs.getString("nombre_curso"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar cursos: " + e.getMessage());
        } finally {
            conexion.desconectar();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difuminado1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfnombres = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfapellidop = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfdepartamento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfapellidom = new javax.swing.JTextField();
        tfprovincia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfdireccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfcorreo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfsexo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfdni = new javax.swing.JTextField();
        Difuminado = new javax.swing.JPanel();
        tfcodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdocente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfduracion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcurso = new javax.swing.JComboBox<>();
        agregurso = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(909, 521));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Difuminado1.setBackground(new java.awt.Color(0, 0, 0, 180));

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Apellido Paterno");

        tfnombres.setEditable(false);
        tfnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombresActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombres");

        tfapellidop.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Apellido Materno");

        tfdepartamento.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Departamento");

        tfapellidom.setEditable(false);

        tfprovincia.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Provincia");

        tfdireccion.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Direción");

        tfcorreo.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Correo");

        tfsexo.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Sexo");

        jLabel22.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DNI");

        tfdni.setEditable(false);
        tfdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Difuminado1Layout = new javax.swing.GroupLayout(Difuminado1);
        Difuminado1.setLayout(Difuminado1Layout);
        Difuminado1Layout.setHorizontalGroup(
            Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Difuminado1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Difuminado1Layout.createSequentialGroup()
                        .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfnombres)
                                .addComponent(tfapellidop)
                                .addComponent(tfapellidom, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addComponent(tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Difuminado1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Difuminado1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Difuminado1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdni, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        Difuminado1Layout.setVerticalGroup(
            Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Difuminado1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfapellidop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfapellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Difuminado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(Difuminado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 410, 360));

        Difuminado.setBackground(new java.awt.Color(0, 0, 0, 180));

        tfcodigo.setEditable(false);
        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo");

        tfdocente.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Docente");

        tfduracion.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Duracion");

        jcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcursoActionPerformed(evt);
            }
        });

        agregurso.setBackground(new java.awt.Color(0, 255, 0));
        agregurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        agregurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregursoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Curso");

        javax.swing.GroupLayout DifuminadoLayout = new javax.swing.GroupLayout(Difuminado);
        Difuminado.setLayout(DifuminadoLayout);
        DifuminadoLayout.setHorizontalGroup(
            DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifuminadoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
            .addGroup(DifuminadoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(agregurso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DifuminadoLayout.setVerticalGroup(
            DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifuminadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(Difuminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 410, 370));

        titulo.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("DATOS DEL ALUMNO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        titulo1.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("AGREGAR MATRÍCULA");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/REGRE.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 70, 50));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregursoActionPerformed
      String cursoSeleccionado = (String) jcurso.getSelectedItem();
        String codigoCurso = tfcodigo.getText();
        String docente = tfdocente.getText();

        if (cursoSeleccionado == null || cursoSeleccionado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un curso.");
            return;
        }

        if (docente == null || docente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El curso seleccionado no tiene docente asignado. Por favor, elija otro curso.");
            return;
        }

        Conexion conexion = new Conexion();
        try (Connection con = conexion.conectar();
             PreparedStatement verificarMatricula = con.prepareStatement(
                     "SELECT * FROM matriculas WHERE id_alumno = ? AND id_curso = ?");
             PreparedStatement registrarMatricula = con.prepareStatement(
                     "INSERT INTO matriculas (id_alumno, id_curso) VALUES (?, ?)");) {
            int idEstudiante = obtenerIdEstudiante(); 
            int idCurso = obtenerIdCurso(codigoCurso); 
            verificarMatricula.setInt(1, idEstudiante);
            verificarMatricula.setInt(2, idCurso);
            try (ResultSet rs = verificarMatricula.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Ya estás matriculado en este curso.");
                    return;
                }
            }
            registrarMatricula.setInt(1, idEstudiante);
            registrarMatricula.setInt(2, idCurso);
            registrarMatricula.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Matrícula realizada con éxito!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al matricularse: " + e.getMessage());
        } finally {
            conexion.desconectar();
        }
    }//GEN-LAST:event_agregursoActionPerformed

    private void tfnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombresActionPerformed

    private void tfdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdniActionPerformed

    private void jcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcursoActionPerformed
    String cursoSeleccionado = (String) jcurso.getSelectedItem();
        if (cursoSeleccionado != null) {
            Conexion conexion = new Conexion();
            try (Connection con = conexion.conectar();
                 PreparedStatement ps = con.prepareStatement(
                     "SELECT c.Codigo, c.Duracion, CONCAT(d.Nombres, ' ', d.Apellidos) AS docente " +
                     "FROM cursos c " +
                     "LEFT JOIN carga_lectiva cl ON c.id_curso = cl.id_Curso " +
                     "LEFT JOIN docentes d ON cl.id_Docente = d.id_docente " +
                     "WHERE c.nombre_curso = ?")) {
                ps.setString(1, cursoSeleccionado);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        tfcodigo.setText(rs.getString("Codigo"));
                        tfduracion.setText(String.valueOf(rs.getInt("Duracion")));
                        tfdocente.setText(rs.getString("docente"));
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontraron datos para el curso seleccionado.");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al obtener datos del curso: " + e.getMessage());
            } finally {
                conexion.desconectar();
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jcursoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    FrmMenuAlumno vermenu = new FrmMenuAlumno();
    vermenu.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void informacion(){
        try{
        String DNI = Login.tfUser.getText();
        String consultar = "SELECT *FROM alumnos WHERE DNI = '"+DNI+"'";
        Statement st = cn.conectar().createStatement();
        ResultSet rs = st.executeQuery(consultar);
        if(rs.next()){
           this.tfdni.setText(DNI);
           this.tfnombres.setText(rs.getString("Nombres"));
           this.tfapellidop.setText(rs.getString("Apellido_Paterno"));
           this.tfapellidom.setText(rs.getString("Apellido_Materno"));
           this.tfdepartamento.setText(rs.getString("Departamento"));
           this.tfprovincia.setText(rs.getString("Provincia"));
           this.tfdireccion.setText(rs.getString("Direccion"));
           this.tfsexo.setText(rs.getString("Sexo"));
           this.tfcorreo.setText(rs.getString("Correo"));
        }
        }catch(SQLException ex){
        }
    }
     private int obtenerIdEstudiante() {
         Conexion conexion = new Conexion();
    int idEstudiante = -1;
    try (Connection con = conexion.conectar();
         PreparedStatement ps = con.prepareStatement("SELECT id_alumno FROM alumnos WHERE DNI = ?")) {
        ps.setString(1, Login.tfUser.getText());
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                idEstudiante = rs.getInt("id_alumno");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener ID del estudiante: " + e.getMessage());
    }
    return idEstudiante; 
    }

    private int obtenerIdCurso(String codigoCurso) {
        Conexion conexion = new Conexion();
    int idCurso = -1;
    try (Connection con = conexion.conectar();
         PreparedStatement ps = con.prepareStatement("SELECT id_curso FROM cursos WHERE Codigo = ?")) {
        ps.setString(1, codigoCurso);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                idCurso = rs.getInt("id_curso");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener ID del curso: " + e.getMessage());
    }
    return idCurso;
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Difuminado;
    private javax.swing.JPanel Difuminado1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton agregurso;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcurso;
    private javax.swing.JTextField tfapellidom;
    private javax.swing.JTextField tfapellidop;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfcorreo;
    private javax.swing.JTextField tfdepartamento;
    private javax.swing.JTextField tfdireccion;
    private javax.swing.JTextField tfdni;
    private javax.swing.JTextField tfdocente;
    private javax.swing.JTextField tfduracion;
    private javax.swing.JTextField tfnombres;
    private javax.swing.JTextField tfprovincia;
    private javax.swing.JTextField tfsexo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
