/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package USC;

import connections_bd.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmVerMatricula extends javax.swing.JFrame {

    /**
     * Creates new form FrmVerMatricula
     */
    Conexion cn;
    DefaultTableModel modelo;
    public FrmVerMatricula() {
        initComponents();
        setLocationRelativeTo(this);
        cn=new Conexion();
        cn.conectar();
        modelo = (DefaultTableModel) tabla.getModel();
        rsscalelabel.RSScaleLabel.setScaleLabel(Fondo,"src/Recursos/Fondodef.jpg");
        informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difuminado = new javax.swing.JPanel();
        Foto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfapellidop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdepartamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfapellidom = new javax.swing.JTextField();
        tfprovincia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfsexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfdni = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(909, 521));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Difuminado.setBackground(new java.awt.Color(0, 0, 0, 180));

        Foto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");

        tfnombres.setEditable(false);
        tfnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres");

        tfapellidop.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido Materno");

        tfdepartamento.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departamento");

        tfapellidom.setEditable(false);

        tfprovincia.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Provincia");

        tfdireccion.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direción");

        tfcorreo.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");

        tfsexo.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sexo");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DNI");

        tfdni.setEditable(false);
        tfdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DifuminadoLayout = new javax.swing.GroupLayout(Difuminado);
        Difuminado.setLayout(DifuminadoLayout);
        DifuminadoLayout.setHorizontalGroup(
            DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifuminadoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfnombres)
                                .addComponent(tfapellidop)
                                .addComponent(tfapellidom, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addComponent(tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdni))
                    .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        DifuminadoLayout.setVerticalGroup(
            DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifuminadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfapellidop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfapellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfdni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DifuminadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DifuminadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Difuminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 330));

        titulo.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("MATRÍCULA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Curso", "Código", "Docente"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 310, 330));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/REGRE.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 70, 50));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    FrmMenuAlumno vermenu = new FrmMenuAlumno();
    vermenu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombresActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_tfnombresActionPerformed

    private void tfdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdniActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_tfdniActionPerformed

    /**
     * @param args the command line arguments
     */
    public void informacion(){
        try{
        String DNI = Login.tfUser.getText();
        String consultar = "SELECT *FROM alumnos WHERE DNI = '"+DNI+"'";
        Statement st = cn.conectar().createStatement();
        ResultSet rs = st.executeQuery(consultar);
        if(rs.next()){
           this.tfdni.setText(DNI);
           this.tfnombres.setText(rs.getString("Nombres"));
           this.tfapellidop.setText(rs.getString("Apellido_Paterno"));
           this.tfapellidom.setText(rs.getString("Apellido_Materno"));
           this.tfdepartamento.setText(rs.getString("Departamento"));
           this.tfprovincia.setText(rs.getString("Provincia"));
           this.tfdireccion.setText(rs.getString("Direccion"));
           this.tfsexo.setText(rs.getString("Sexo"));
           this.tfcorreo.setText(rs.getString("Correo"));
           int idEstudiante = rs.getInt("id_alumno");
            listarmatricula(idEstudiante);
        }
        }catch(SQLException ex){
        }
    }
   public void listarmatricula(int idEstudiante) {
    try {
        limpiarTabla(); 
       String listar = "SELECT c.Codigo, c.nombre_curso, " + "CONCAT(d.Nombres, ' ', d.Apellidos) AS docente " + "FROM matriculas m " + "INNER JOIN cursos c ON m.id_curso = c.id_curso " +"LEFT JOIN carga_lectiva cl ON c.id_curso = cl.id_Curso " +    "LEFT JOIN docentes d ON cl.id_Docente = d.id_docente " +     "WHERE m.id_alumno = ?";
        PreparedStatement ps = cn.conectar().prepareStatement(listar);
        ps.setInt(1, idEstudiante);
        ResultSet rs = ps.executeQuery();
        Object[] fila = new Object[3];
        modelo = (DefaultTableModel) tabla.getModel();
        while (rs.next()) {
            fila[0] = rs.getString("Codigo");       
            fila[1] = rs.getString("nombre_curso");
            fila[2] = rs.getString("docente");      
            modelo.addRow(fila);
        }
        tabla.setModel(modelo); 
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al listar las matrículas: " + e.getMessage());
    }
}
      void limpiarTabla(){
      while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
         }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVerMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVerMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVerMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVerMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVerMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Difuminado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tfapellidom;
    private javax.swing.JTextField tfapellidop;
    private javax.swing.JTextField tfcorreo;
    private javax.swing.JTextField tfdepartamento;
    private javax.swing.JTextField tfdireccion;
    private javax.swing.JTextField tfdni;
    private javax.swing.JTextField tfnombres;
    private javax.swing.JTextField tfprovincia;
    private javax.swing.JTextField tfsexo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
