/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package USC;

import connections_bd.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {
FrmMenu vermenu=new FrmMenu();
FrmMenuAlumno vermenualumno=new FrmMenuAlumno();
    Conexion cn;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Inicio de sesión");
        cn = new Conexion();
        cn.conectar();
        this.setDefaultCloseOperation(0);
        this.setResizable(false);
        iconinvisible.setVisible(false);
     
        rsscalelabel.RSScaleLabel.setScaleLabel(UserLabel,"src/Recursos/User.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Fondo,"src/Recursos/6057485.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconuser,"src/Recursos/usuario.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconpassword,"src/Recursos/contraseña.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconvisible,"src/Recursos/visible.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconinvisible,"src/Recursos/invisible.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difuminado = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        IconUser = new javax.swing.JPanel();
        iconuser = new javax.swing.JLabel();
        IconPassword = new javax.swing.JPanel();
        iconpassword = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        separador1 = new javax.swing.JSeparator();
        tfUser = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        separador2 = new javax.swing.JSeparator();
        tfPassword = new javax.swing.JPasswordField();
        iconvisible = new javax.swing.JLabel();
        iconinvisible = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(673, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Difuminado.setBackground(new java.awt.Color(0, 0, 0, 180));
        Difuminado.setBorder(new javax.swing.border.MatteBorder(null));
        Difuminado.setForeground(new java.awt.Color(153, 153, 153));
        Difuminado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel.setBorder(new javax.swing.border.MatteBorder(null));
        Difuminado.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, 80));

        IconUser.setBackground(new java.awt.Color(255, 255, 255));
        IconUser.setPreferredSize(new java.awt.Dimension(32, 32));
        IconUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IconUser.add(iconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        Difuminado.add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 40, 40));

        IconPassword.setBackground(new java.awt.Color(255, 255, 255));
        IconPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IconPassword.add(iconpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        Difuminado.add(IconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 40));

        UserPanel.setBackground(new java.awt.Color(255, 255, 255));
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separador1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        UserPanel.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        tfUser.setBackground(new java.awt.Color(0, 0, 0, 0));
        tfUser.setBorder(null);
        tfUser.setSelectionColor(new java.awt.Color(255, 255, 255));
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        UserPanel.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        Difuminado.add(UserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, 40));

        PasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PasswordPanel.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        tfPassword.setBackground(new java.awt.Color(0, 0, 0, 0));
        tfPassword.setBorder(null);
        PasswordPanel.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        iconvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconvisibleMouseClicked(evt);
            }
        });
        PasswordPanel.add(iconvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 40, 40));

        iconinvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconinvisibleMouseClicked(evt);
            }
        });
        PasswordPanel.add(iconinvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 40, 40));

        Difuminado.add(PasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 220, 40));

        btnIngresar.setBackground(new java.awt.Color(102, 204, 255));
        btnIngresar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ingresar.png"))); // NOI18N
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btnIngresar.setBorderPainted(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.setRequestFocusEnabled(false);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        Difuminado.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 80, 50));

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salir.png"))); // NOI18N
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setRequestFocusEnabled(false);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        Difuminado.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 80, 50));

        getContentPane().add(Difuminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 360, 430));

        jPanel1.setPreferredSize(new java.awt.Dimension(673, 506));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setPreferredSize(new java.awt.Dimension(673, 506));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 673, 506));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 673, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
    btnIngresar.setBackground(new java.awt.Color(0, 0, 102));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void iconvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconvisibleMouseClicked
    iconvisible.setVisible(false);
    iconinvisible.setVisible(true);
    tfPassword.setEchoChar((char)0);
        // TODO add your handling code here:
    }//GEN-LAST:event_iconvisibleMouseClicked

    private void iconinvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconinvisibleMouseClicked
    iconvisible.setVisible(true);
    iconinvisible.setVisible(false);
    tfPassword.setEchoChar('*');
        // TODO add your handling code here:
    }//GEN-LAST:event_iconinvisibleMouseClicked

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
    btnIngresar.setBackground(new java.awt.Color(51, 102, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

    String usuario = tfUser.getText();  
    String contraseña = new String(tfPassword.getPassword()); 
    String consulta = "SELECT * FROM usuarios WHERE DNI = ? AND contraseña = ?";
    try (Connection conn = cn.conectar(); 
         PreparedStatement pstmt = conn.prepareStatement(consulta)) {
        pstmt.setString(1, usuario);  
        pstmt.setString(2, contraseña); 
        try (ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                String tipoUsuario = rs.getString("tipo_usuario");
                if (tipoUsuario.equals("admin")) {                   
                    JOptionPane.showMessageDialog(null, "Se ingresó como administrador");
                    FrmMenu vermenu = new FrmMenu();
                    vermenu.setVisible(true);
                    this.setVisible(false);
                } else if (tipoUsuario.equals("estudiante")) {                   
                    JOptionPane.showMessageDialog(null, "DNI y contraseña correctos, ingresó como estudiante");
                    FrmMenuAlumno vermenualumno = new FrmMenuAlumno();
                    vermenualumno.setVisible(true);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "DNI o contraseña incorrectos");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error en el Sistema." + e.getMessage());
    }

    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
    btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
    btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Difuminado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel IconPassword;
    private javax.swing.JPanel IconUser;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel iconinvisible;
    private javax.swing.JLabel iconpassword;
    private javax.swing.JLabel iconuser;
    private javax.swing.JLabel iconvisible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JPasswordField tfPassword;
    public static javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
